### ISSUE TITLE
Hero gold and kill credits incorrectly displayed

### ISSUE THREAD

**Issue by NoFluxGiven** [bmddota/barebones#16]
Not sure what's causing it, but some mods that use the barebones framework display incorrect gold values on Hero kills (eg. "Tusk pwned Storm Spirit for 0 gold!"), and on building kills, it claims that they were killed by a neutral creep.

I've extensively tested this and it is consistently reproduced. The debug prints (OnTeamKillCredit(), OnEntityKilled()) show that it is in fact attributed to the correct team, but they grant no comeback gold as in regular DotA, and no gold splits occur when a Hero is killed by a tower or creep on the opposite team.

Is there anything in Barebones that would possibly interfere with this system in DotA? It is a pain for mods that are using the original DotA map and are "DotA-esque".

**Comment by bmddota** [comment]
Some settings could be doing this, like
USE_STANDARD_HERO_GOLD_BOUNTY 

or

LOSE_GOLD_ON_DEATH 

or 

USE_CUSTOM_HERO_LEVELS 

Some of these values may need to be set to false or nil to get the appropriate default behavior.  These things unfortunately break sometimes just from Valve making updates.

**Comment by NoFluxGiven** [comment]
Yeah, it appears to be that a nil value (or just not setting some of those) is the only way to go. Some of the recent updates have appeared to break some of the GameMode settings in other ways, unfortunately. Hopefully Valve will step up and fix some of these issues; for now, I'll avoid using those settings.
