### ISSUE TITLE
Having an enemy hero selected die while having the shop open and suggested items disabled causes the suggested items tab to open

### ISSUE THREAD

**Issue by ggassmann** [bmddota/barebones#7]
```
UNIVERSAL_SHOP_MODE = false
RECOMMENDED_BUILDS_DISABLED = true
SHOW_ONLY_PLAYER_INVENTORY = false
DISABLE_STASH_PURCHASING = true
```

Create an enemy hero and send him into the jungle to die

Open shop in fountain with the enemy hero still selected.

When the enemy hero dies, the suggested items panel will open.

![image](https://cloud.githubusercontent.com/assets/1059365/8347995/f541c976-1ad2-11e5-86e7-73f42dca25ba.png)

**Comment by bmddota** [comment]
This isn't specifically linked to barebones, and sounds like just a regular Dota issue (potentially having to do with the recommended build disable setting).  I suggest posting a report to dev.dota2.com/
