### ISSUE TITLE
Notifications.lua hero/image/ability/item examples not working

### ISSUE THREAD

**Issue by veggiesama** [bmddota/barebones#8]
Text examples work, but I have been unable to get any type of image to show up as part of a notification. Instead of displaying an image, I see "No Text provided."

**Comment by veggiesama** [comment]
Here's what the following code looks like:

`
Notifications:BottomToAll({hero="npc_dota_hero_night_stalker", duration=5.0})
Notifications:BottomToAll({text="The Night Stalker has evolved!", duration=5.0, continue=true})
Notifications:TopToAll({image="file://{images}/status_icons/dota_generic.psd", duration=5.0})
Notifications:TopToAll({ability="nyx_assassin_mana_burn", continue=true})
Notifications:TopToAll({item="item_force_staff", continue=true})`

![notification](https://cloud.githubusercontent.com/assets/2153575/9148538/92a3977a-3d4d-11e5-9f3c-467377bc1b70.png)

**Comment by bmddota** [comment]
HI veggiesama.  I was away at TI so it took a bit to see this.  It looks like you're using an older version of notificiations.lua and not the most up to date package.  Your notifications version should be 0.88 which you can find at the top of the notifications.lua fille.  Make sure you update the notifications.lua file and the corresponding panorama files as well.

You can see the current version and follow the instructions here https://github.com/bmddota/barebones/blob/source2/game/dota_addons/barebones/scripts/vscripts/libraries/notifications.lua#L1-L8

**Comment by veggiesama** [comment]
Thanks. I had version 0.88 of notifications.lua but it turned out that barebones_hud_base.js in the panorama folder had some changes. Seems to work now!
